services:
  database:
    image: postgres:17
    volumes:
      - psql_data:/var/lib/postgresql/data:rw
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=holidays
    networks:
      - net-1
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready -U app"
      interval: 10s
      timeout: 5s
      retries: 100
      start_period: 10s

  data_updater:
    build:
      context: .
      dockerfile: ./docker/updater/Dockerfile
    environment:
      - TZ=Asia/Tokyo
    depends_on:
      database:
        condition: service_healthy
    networks:
      - net-1
  
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    environment:
      - TZ=Asia/Tokyo
      - LOG_LEVEL=debug
    depends_on:
      database:
        condition: service_healthy
    networks:
      - net-1
    volumes:
      - ./src:/go/app:rw
    ports:
      - "8080:8080"
  
  key_manager:
    build:
      context: .
      dockerfile: ./docker/key_management/Dockerfile
    environment:
      - TZ=Asia/Tokyo
      - LOG_LEVEL=info
    depends_on:
      database:
        condition: service_healthy
    networks:
      - net-1
    volumes:
      - ./src:/go/app:rw
    ports:
      - "8081:8080"
  

volumes:
  psql_data:

networks:
  net-1:
