services:
  database:
    image: postgres:16
    volumes:
      - psql_data:/var/lib/postgresql/data:rw
    restart: always
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=holidays
    networks:
      - net-1
    ports:
      - "5432:5432"

  data_updater:
    build:
      context: .
      dockerfile: ./docker/updater/Dockerfile
    environment:
      - TZ=Asia/Tokyo
    depends_on:
      - database
    networks:
      - net-1
  
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    environment:
      - TZ=Asia/Tokyo
      - LOG_LEVEL=debug
    depends_on:
      - database
    networks:
      - net-1
    volumes:
      - ./src:/go/app:rw
    ports:
      - 8080:80
  
  key_manager:
    build:
      context: .
      dockerfile: ./docker/key_management/Dockerfile
    environment:
      - TZ=Asia/Tokyo
      - LOG_LEVEL=debug
    depends_on:
      - database
    networks:
      - net-1
    volumes:
      - ./src:/go/app:rw
    ports:
      - 8081:80
  

volumes:
  psql_data:

networks:
  net-1:
